In [12]:
import numpy as np

# 1. 数组创建与索引
a = np.eye(5)
b = np.random.randn(5,5)
c = b[np.where(b>0.5)]
b[np.where(b<=0.5)] = 0
b,c

(array([[0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.55641129, 0.68969632, 0.83200116],
        [0.64295969, 0.        , 0.        , 0.        , 0.5227231 ],
        [0.        , 0.        , 0.        , 0.99200027, 0.        ],
        [0.        , 0.        , 0.83728821, 0.        , 0.        ]]),
 array([0.55641129, 0.68969632, 0.83200116, 0.64295969, 0.5227231 ,
        0.99200027, 0.83728821]))

In [31]:
# 2.广播与计算
a = np.random.randn(3,4)
b = np.random.randn(4,)

# a.shape, b.shape
c = a + b
d = a * b
a,b, c, b.shape
# 为什么(3,4)和(4,)可以广播， 但是(3,4)和(3,)不能广播？
# 广播的规则遵循从右往左对其，前者：4和4对其，补上3，后者：4无法和3对其
# 但是1是特殊的，比如(3,4)可以和(3,1)广播 

(array([[ 0.13025696, -2.52817005, -1.50536594,  0.55944575],
        [-0.56496122,  0.68229976,  0.79360592,  0.70357979],
        [ 0.86870804, -0.75269614, -0.15670218, -0.95926266]]),
 array([-0.34991773, -0.70416769, -0.96291234, -0.16014963]),
 array([[-0.21966078, -3.23233774, -2.46827829,  0.39929612],
        [-0.91487896, -0.02186793, -0.16930642,  0.54343016],
        [ 0.51879031, -1.45686383, -1.11961453, -1.11941229]]),
 (4,))

In [ ]:
# 3.L2归一化
a = np.random.randn(3,4)
print(a)
l2_norm = np.linalg.norm(a, axis=1) # 线性代数库
print(l2_norm)
a = a/l2_norm.reshape(3,1)
print(a)
print( np.linalg.norm(a, axis=1))

[[-0.59409926  0.43917121 -1.76740243  0.01720008]
 [-0.34858123  0.21145965 -0.58112426  1.18982754]
 [-1.72831407 -1.50631098 -0.08318636 -1.15093283]]
[1.91568068 1.38550317 2.56663372]
[[-0.31012437  0.22925074 -0.92259762  0.00897858]
 [-0.2515918   0.152623   -0.41943192  0.85876927]
 [-0.67337776 -0.58688194 -0.03241069 -0.44842114]]
[1. 1. 1.]


In [ ]:
# 4. 性能对比
