In [2]:
import numpy as np

# 1. 数组创建与索引
a = np.eye(5)
b = np.random.randn(5,5)
c = b[np.where(b>0.5)]
b[np.where(b<=0.5)] = 0
b,c

(array([[0.        , 1.65286453, 0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.67884843, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.57644517, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.684555  , 0.        , 0.        , 0.        , 0.        ]]),
 array([1.65286453, 1.67884843, 0.57644517, 0.684555  ]))

In [6]:
# 2.广播与计算
import numpy as np
a = np.random.randn(3,4)
b = np.random.randn(4,)

# a.shape, b.shape
c = a + b
d = a * b
e = a @ b
c.shape, d.shape, e.shape
# 为什么(3,4)和(4,)可以广播， 但是(3,4)和(3,)不能广播？
# 广播的规则遵循从右往左对其，前者：4和4对其，补上3，后者：4无法和3对其
# 但是1是特殊的，比如(3,4)可以和(3,1)广播 

((3, 4), (3, 4), (3,))

In [ ]:
# 3.L2归一化
a = np.random.randn(3,4)
print(a)
l2_norm = np.linalg.norm(a, axis=1, keepdims=True) # 线性代数库
print(l2_norm)
a = a/l2_norm
print(a)
# print( np.linalg.norm(a, axis=1))
# print(np.var(a, axis=1))
# print(np.std(a, axis=1))
np.max(a, axis=1)
np.argmax(a, axis=1, keepdims=True)
# 把每一行最大的元素替换为0

[[ 1.10850798 -0.08033402 -0.92678192 -0.10843134]
 [ 0.4907552  -0.18475024  1.74918533 -0.64581633]
 [ 0.10291579 -1.57059579  0.29233845  0.70913216]]
[[1.45118075]
 [1.93693091]
 [1.75091205]]
[[ 0.76386624 -0.05535769 -0.63863989 -0.07471939]
 [ 0.25336742 -0.09538298  0.90307058 -0.33342249]
 [ 0.05877839 -0.89701581  0.16696353  0.4050073 ]]


array([[0],
       [2],
       [3]], dtype=int64)

In [ ]:
# 4. 对比 Python 循环和 NumPy 向量化操作在求和上的速度差异
# 什么是向量化操作？ 比如我们举个求和的例子

import time
# python 循环
start = time.time()
total = 0
for i in range(1500000):
    total += i
print(total) # 1124999250000
print(f"use_time:{time.time() - start}")

# 向量化操作
start = time.time()
sum = np.sum(np.arange(0,1500000, dtype=np.int64))
print(sum) # -282181552， 默认为int32， 最大值为 2^31
print(f"use_time:{time.time() - start}")

# numpy的整数溢出了

1124999250000
use_time:0.08305788040161133
1124999250000
use_time:0.0035974979400634766
