In [1]:
import numpy as np

In [2]:
# 生成一个1到100的数组
x = np.arange(1, 100)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
# 生成1到100所有的奇数
x = np.arange(1, 100, step=2)

# 形状修改为(5, 10)
x = x.reshape(5, 10)
x

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [ ]:
# 替换第一行和第二行的元素, 高级索引
x[[0, 1]] = x[[1, 0]]
x

# 我的丑陋方式：
# tmp = x[0, :].copy()
# x[0, :] = x[1, :]
# x[1, :] = tmp
# print(x)

array([[21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [11]:
# 随机生成一个只有0到10整数，长度为20的数组
x = np.random.randint(0, 11, size=(20))
print(x)

[ 7  2  0  3  6  5  0  0  1  8  3  9  7 10 10  5  5  5  2  2]


In [ ]:
# 求数组 均值， 方差， 中位数， 众数
mean = np.mean(x)
max = np.max(x)
medi = np.median(x) # 前三种都有现成函数可以调
print(x)
print(f"mean:{mean}, max: {max}, medi: {medi}")

# 求众数
# 我的做法：用字典统计每个数字出现的次数
time_state = {}
for num in x:
    try:
        time_state[num] += 1
    except:
        time_state[num] = 1

max = sorted(time_state.values())[0]

zhongshu = []
for dict in time_state.items():
    if dict[1] == max:
        zhongshu.append(dict[0])
print(zhongshu)
zhongshu = np.mean(zhongshu)
print(f"众数:{zhongshu}")
