In [2]:
import numpy as np

# 1. 数组创建与索引
a = np.eye(5)
b = np.random.randn(5,5)
c = b[np.where(b>0.5)]
b[np.where(b<=0.5)] = 0
b,c

(array([[0.        , 1.65286453, 0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.67884843, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.57644517, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [0.684555  , 0.        , 0.        , 0.        , 0.        ]]),
 array([1.65286453, 1.67884843, 0.57644517, 0.684555  ]))

In [1]:
# 2.广播与计算
import numpy as np
a = np.random.randn(3,4)
b = np.random.randn(4,)

# a.shape, b.shape
c = a + b
d = a * b
e = a @ b
c.shape, d.shape, e.shape
# 为什么(3,4)和(4,)可以广播， 但是(3,4)和(3,)不能广播？
# 广播的规则遵循从右往左对其，前者：4和4对其，补上3，后者：4无法和3对其
# 但是1是特殊的，比如(3,4)可以和(3,1)广播 

((3, 4), (3, 4), (3,))

In [ ]:
# 3.L2归一化
a = np.random.randn(3,4)
print(a)
l2_norm = np.linalg.norm(a, axis=1, keepdims=True) # 线性代数库
print(l2_norm)
a = a/l2_norm
print(a)
# print( np.linalg.norm(a, axis=1))
# print(np.var(a, axis=1))
# print(np.std(a, axis=1))
np.max(a, axis=1)
max_idx = np.argmax(a, axis=1)
# 把每一行最大的元素替换为0
# a[(np.arange(0, 3), max_idx)] = 0
# 另外一种方法： scatter

[[ 0.84815747  0.45282303 -0.23215785 -0.06184365]
 [ 2.28601478  1.18689911 -1.23901186 -1.45955112]
 [ 0.45090011 -0.33349178  1.4666473   0.63561107]]
[[0.99103063]
 [3.20936643]
 [1.69398447]]
[[ 0.85583376  0.45692133 -0.23425901 -0.06240337]
 [ 0.71229472  0.36982349 -0.3860612  -0.45477858]
 [ 0.26617724 -0.19686826  0.86579737  0.37521658]]


array([[ 0.        ,  0.45692133, -0.23425901, -0.06240337],
       [ 0.        ,  0.36982349, -0.3860612 , -0.45477858],
       [ 0.26617724, -0.19686826,  0.        ,  0.37521658]])

In [ ]:
# 4. 对比 Python 循环和 NumPy 向量化操作在求和上的速度差异
# 什么是向量化操作？ 比如我们举个求和的例子

import time
# python 循环
start = time.time()
total = 0
for i in range(1500000):
    total += i
print(total) # 1124999250000
print(f"use_time:{time.time() - start}")

# 向量化操作
start = time.time()
sum = np.sum(np.arange(0,1500000, dtype=np.int64))
print(sum) # -282181552， 默认为int32， 最大值为 2^31
print(f"use_time:{time.time() - start}")

# numpy的整数溢出了

1124999250000
use_time:0.08305788040161133
1124999250000
use_time:0.0035974979400634766


In [2]:
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BL

In [7]:
import torch
x = torch.randn(3, 4)
print(x)


# idx = torch.argmax(x, dim=1)
# y[(torch.arange(0,3), idx)] = 0
# print(y)

# 第二种方式, scatter
idx = torch.argmax(x, dim=1, keepdim=True)
y2 = x.scatter(1, idx, 0)
print(y2)

tensor([[ 1.2103,  0.1172, -1.3678,  0.9445],
        [-1.4095, -0.4206,  1.0324, -2.6607],
        [ 0.2056, -0.2114, -1.9949, -0.1871]])
tensor([[ 0.0000,  0.1172, -1.3678,  0.9445],
        [-1.4095, -0.4206,  0.0000, -2.6607],
        [ 0.0000, -0.2114, -1.9949, -0.1871]])
